apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: jvcr-dev-tls
spec:
  secretName: jvcr-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jvcr.dev
  dnsNames:
    - jvcr.dev
    - www.jvcr.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - jvcr.dev
          - www.jvcr.dev
